# Application properties for the project

spring:
  application:
    name: Patient-Service
  profiles:
    active: dev

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 8080